services:
  reservations-service:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development

    command: pnpm run start:dev reservations

    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

    env_file:
      - ./apps/reservations/.env

    container_name: hyperlocal-nest-reservations-service
    restart: unless-stopped
    depends_on:
      - mongo

  auth-service:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development

    command: pnpm run start:dev auth

    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

    env_file:
      - ./apps/auth/.env

    container_name: hyperlocal-nest-auth-service
    restart: unless-stopped
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: hyperlocal-nest-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: